#!/system/bin/sh

# Variable
doGov=1

# enable the interactive governor by default
busybox mount -o remount,rw /system
if busybox [ $doGov -eq 1 ]; then
insmod /system/lib/modules/symsearch.ko
insmod /system/lib/modules/cpufreq_interactive.ko
echo interactive > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
fi