#!/system/bin/sh

# Variables
doOnboot=0
doLoop=1
doBuild=1

busybox mount -o remount,rw /system

# file system speedups
busybox mount -o remount,noatime,barrier=0,nobh /system
busybox mount -o remount,noatime,barrier=0,nobh /data
busybox mount -o remount,noatime,barrier=0,nobh /cache

# sd card speed boost
if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]; then
echo 1024 > /sys/devices/virtual/bdi/179:0/read_ahead_kb

# build.prop edits
	if busybox [ $doBuild -eq 1 ]; then
	busybox cp -f /system/build.prop /data/mods/
	busybox sed -i 's|doBuild=.*|doBuild=0|' /system/etc/init.d/99mods
	busybox sed -i 's|windowsmgr.max_events_per_sec=.*|windowsmgr.max_events_per_sec=95|' /system/build.prop
	busybox sed -i 's|wifi.supplicant_scan_interval = .*|wifi.supplicant_scan_interval = 180|' /system/build.prop
	busybox sed -i 's|dalvik.vm.heapsize=.*|dalvik.vm.heapsize=50m|' /system/build.prop
	busybox sed -i 's|mot.proximity.delay=.*|mot.proximity.delay=100|' /system/build.prop
	busybox sed -i 's|ro.telephony.call_ring.delay=.*|ro.telephony.call_ring.delay=750|' /system/build.prop
	busybox sed -i 's|ro.build.display.id=.*|ro.build.display.id=OTAGB_JakebitesModsv9|' /system/build.prop

# Loop first boot for build.prop
		if [ $doLoop -eq 1 ]; then
		busybox sed -i 's|doLoop=.*|doLoop=0|' /system/etc/init.d/99mods
		reboot
		fi
	fi
fi