#!/system/bin/sh

# Variable
doGov=1

# enable the InteractiveX governor by default
busybox mount -o remount,rw /system
if busybox [ $doGov -eq 1 ]; then
insmod /system/lib/modules/cpufreq_interactivex.ko nr_running_addr=0xc005e844 
echo interactiveX > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
fi