#!/system/bin/sh

# Mods!

# Variables
doMods=1

# Functions

sysctlMods()
{
	if busybox [ -n "$( busybox grep doSysctl=1 /system/etc/init.d/99sysctl )" ]; then
	echo -n "Sysctl tweaks are currently running, would you like to turn them off? (y/n) : "
		read sysctlonMod
		case $sysctlonMod in
			y|Y)
				busybox mount -o remount,rw /system
				busybox sed -i 's|doSysctl=.*|doSysctl=0|' /system/etc/init.d/99sysctl
				echo
				echo
				echo "Sysctl tweaks disabled."
				echo -n "You must reboot for the changes to take effect, reboot now? (y/n) : "
				read rebootNow
				case $rebootNow in
					y|Y)
						reboot
					;;
				esac		
				echo
				echo
			;;
			n|N)
				echo
				echo
				echo -n "Sysctl tweaks remain enabled, press enter to continue: "
				read anyKeymenu
				case $anyKeymenu in
					*)
					;;
				esac
				echo
				echo
			;;			
		esac
	else
	echo -n "Sysctl tweaks are currently not running, would you like to turn them on? (y/n) : "
		read sysctloffMod
		case $sysctloffMod in
			y|Y)
				busybox mount -o remount,rw /system
				busybox sed -i 's|doSysctl=.*|doSysctl=1|' /system/etc/init.d/99sysctl
				echo
				echo
				echo "Sysctl tweaks enabled."
				echo -n "You must reboot for the changes to take effect, reboot now? (y/n) : "
				read rebootNow
				case $rebootNow in
					y|Y)
						reboot
					;;
				esac
				echo
				echo
			;;
			n|N)
				echo
				echo
				echo -n "Sysctl tweaks remain disabled, press enter to continue: "
				read anyKeymenu
				case $anyKeymenu in
					*)
					;;
				esac
				echo
				echo
			;;			
		esac
	fi
}

cronMods()
{
	if busybox [ -n "$( busybox grep doCron=1 /system/etc/init.d/99cron )" ]; then
	echo -n "The cron service is currently running, would you like to turn it off? (y/n) : "
		read crononMod
		case $crononMod in
			y|Y)
				busybox mount -o remount,rw /system
				busybox sed -i 's|doCron=.*|doCron=0|' /system/etc/init.d/99cron
				echo
				echo
				echo "Cron service disabled."
				echo -n "You must reboot for the changes to take effect, reboot now? (y/n) : "
				read rebootNow
				case $rebootNow in
					y|Y)
						reboot
					;;
				esac
			;;
			n|N)
				echo
				echo
				echo -n "Cron service remain enabled, press enter to continue: "
				read anyKeymenu
				case $anyKeymenu in
					*)
					;;
				esac
				echo
				echo
			;;			
		esac
	else
	echo -n "The cron service is currently not running, would you like to turn it on? (y/n) : "
		read cronoffMod
		case $cronoffMod in
			y|Y)
				busybox mount -o remount,rw /system
				busybox sed -i 's|doCron=.*|doCron=1|' /system/etc/init.d/99cron
				echo
				echo
				echo "Cron service enabled."
				echo -n "You must reboot for the changes to take effect, reboot now? (y/n) : "
				read rebootNow
				case $rebootNow in
					y|Y)
						reboot
					;;
				esac
			;;
			n|N)
				echo
				echo
				echo -n "The cron service remains disabled, press enter to continue: "
				read anyKeymenu
				case $anyKeymenu in
					*)
					;;
				esac
				echo
				echo
			;;			
		esac
	fi
}

loggerMods()
{
	if busybox [ -n "$( busybox grep doLogger=1 /system/etc/init.d/99logger )" ]; then
	echo -n "The logger is currently disabled, would you like to turn it on? (y/n) : "
		read loggeronMod
		case $loggeronMod in
			y|Y)
				busybox mount -o remount,rw /system
				busybox sed -i 's|doLogger=.*|doLogger=0|' /system/etc/init.d/99logger
				echo
				echo
				echo "Logger enabled."
				echo -n "You must reboot for the changes to take effect, reboot now? (y/n) : "
				read rebootNow
				case $rebootNow in
					y|Y)
						reboot
					;;
				esac
			;;
			n|N)
				echo
				echo
				echo -n "Logger remains disabled, press enter to continue: "
				read anyKeymenu
				case $anyKeymenu in
					*)
					;;
				esac
				echo
				echo
			;;			
		esac
	else
	echo -n "The logger is currently enabled, would you like to turn it off? (y/n) : "
		read loggeroffMod
		case $loggeroffMod in
			y|Y)
				busybox mount -o remount,rw /system
				busybox sed -i 's|doLogger=.*|doLogger=1|' /system/etc/init.d/99logger
				echo
				echo
				echo "Logger disabled."
				echo -n "You must reboot for the changes to take effect, reboot now? (y/n) : "
				read rebootNow
				case $rebootNow in
					y|Y)
						reboot
					;;
				esac
			;;
			n|N)
				echo
				echo
				echo -n "The logger remains enabled, press enter to continue: "
				read anyKeymenu
				case $anyKeymenu in
					*)
					;;
				esac
				echo
				echo
			;;			
		esac
	fi
}

govMods()
{
	if busybox [ -n "$( busybox grep doGov=1 /system/etc/init.d/99gov )" ]; then
	echo -n "The InteractiveX governor is currently enabled, would you like to turn it off? (y/n) : "
		read govonMod
		case $govonMod in
			y|Y)
				busybox mount -o remount,rw /system
				busybox sed -i 's|doGov=.*|doGov=0|' /system/etc/init.d/99gov
				echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
				echo
				echo
				echo -n "The InteractiveX governor has been disabled and the ondemand governor has been restored, press enter to continue: "
				read anyKeymenu
				case $anyKeymenu in
					*)
					;;
				esac
				echo
				echo
			;;
			n|N)
				echo
				echo
				echo -n "The InteractiveX governor remains enabled, press enter to continue: "
				read anyKeymenu
				case $anyKeymenu in
					*)
					;;
				esac
				echo
				echo
			;;			
		esac
	else
	echo -n "The InteractiveX governor is currently disabled, would you like to turn it on? (y/n) : "
		read govoffMod
		case $govoffMod in
			y|Y)
				busybox mount -o remount,rw /system
				busybox sed -i 's|doGov=.*|doGov=1|' /system/etc/init.d/99gov
				echo InteractiveX > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
				echo
				echo
				echo -n "The InteractiveX governor has been enabled, press enter to continue: "
				read anyKeymenu
				case $anyKeymenu in
					*)
					;;
				esac
				echo
				echo
			;;
			n|N)
				echo
				echo
				echo -n "The InteractiveX governor remains disabled, the ondemand governor is currently running, press enter to continue: "
				read anyKeymenu
				case $anyKeymenu in
					*)
					;;
				esac
				echo
				echo
			;;			
		esac
	fi
}

zipMods()
{
	if busybox [ -n "$( busybox grep doZip=1 /system/etc/init.d/99zip )" ]; then
	echo -n "The zipalign at boot mod is currently running, would you like to turn it off? (y/n) : "
		read ziponMod
		case $ziponMod in
			y|Y)
				busybox mount -o remount,rw /system
				busybox sed -i 's|doZip=.*|doZip=0|' /system/etc/init.d/99zip
				echo
				echo
				echo "Zipalign at boot has been disabled."
				echo -n "You must reboot for the changes to take effect, reboot now? (y/n) : "
				read rebootNow
				case $rebootNow in
					y|Y)
						reboot
					;;
				esac
			;;
			n|N)
				echo
				echo
				echo -n "Zipalign at boot remains enabled, press enter to continue: "
				read anyKeymenu
				case $anyKeymenu in
					*)
					;;
				esac
				echo
				echo
			;;			
		esac
	else
	echo -n "The zipalign at boot mod is currently not running, would you like to turn it on? (y/n) : "
		read zipoffMod
		case $zipoffMod in
			y|Y)
				busybox mount -o remount,rw /system
				busybox sed -i 's|doZip=.*|doZip=1|' /system/etc/init.d/99zip
				echo
				echo
				echo "Zipalign at boot has been enabled."
				echo -n "You must reboot for the changes to take effect, reboot now? (y/n) : "
				read rebootNow
				case $rebootNow in
					y|Y)
						reboot
					;;
				esac
			;;
			n|N)
				echo
				echo
				echo -n "Zipalign at boot remains disabled, press enter to continue: "
				read anyKeymenu
				case $anyKeymenu in
					*)
					;;
				esac
				echo
				echo
			;;			
		esac
	fi
}

doSupercharge()
{
	echo
	echo -n "This will take you to the V6 Supercharger(v8) script by zeppelinrox. Would you like to continue? (y/n) : "
	read superCharge
	case $superCharge in
		y|Y)
			busybox sh /system/xbin/v6supercharger8.sh
		;;
		n|N)
			exit
		;;
	esac
}

bootRecovery()
{
	if busybox [ -n "$( busybox grep doRecovery=1 /system/etc/init.d/99recovery )" ]; then
	echo -n "Recovery on each reboot is currently enabled, would you like to turn it off? (y/n) : "
		read recoveryoffMod
		case $recoveryoffMod in
			y|Y)
				busybox mount -o remount,rw /system
				busybox sed -i 's|doRecovery=.*|doRecovery=0|' /system/etc/init.d/99recovery
				echo
				echo
				echo "Recovery at boot disabled, press enter to continue: "
				read anyKeymenu
				case $anyKeymenu in
					*)
					;;
				esac
			;;
			n|N)
				echo
				echo
				echo -n "Recovery at boot remains enabled, press enter to continue: "
				read anyKeymenu
				case $anyKeymenu in
					*)
					;;
				esac
			;;			
		esac
	else
	echo -n "Recovery on each reboot is currently disabled, would you like to turn it on? (y/n) : "
		read recoveryonMod
		case $recoveryonMod in
			y|Y)
				busybox mount -o remount,rw /system
				busybox sed -i 's|doRecovery=.*|doRecovery=1|' /system/etc/init.d/99recovery
				busybox echo 1 > /data/.recovery_mode; sync;
				echo
				echo
				echo "Recovery at boot enabled, press enter to continue: "
				read anyKeymenu
				case $anyKeymenu in
					*)
					;;
				esac
			;;
			n|N)
				echo
				echo
				echo -n "Recovery at boot remains disabled, press enter to continue: "
				read anyKeymenu
				case $anyKeymenu in
					*)
					;;
				esac
			;;			
		esac
	fi
}


undervoltMods()
{	
	freq=$1
	echo
	echo
	echo -n "This will install, activate and set the ${freq} overclock/undervolt mods at boot. Would you like to continue? (y/n) : "
	read goOcuv
	case $goOcuv in
		y|Y)
			busybox mount -o remount,rw /system
			echo 1 > /data/.recovery_mode; sync;
			busybox cp -f /data/oc/${freq}/99oc /system/etc/init.d/
			busybox chmod 755 /system/etc/init.d/99oc
			busybox sed -i 's|doSleep=.*|doSleep=0|' /system/etc/init.d/99oc
			busybox sh /system/etc/init.d/99oc
			busybox sed -i 's|doOverclock=.*|doOverclock=1|' /system/etc/init.d/99oc
			busybox sed -i 's|doSleep=.*|doSleep=1|' /system/etc/init.d/99oc
			echo
			echo
			echo -n "The ${freq} overclock/undervolt mods have been activated and set at boot. Press enter to show the new/current CPU info: "
			read anyKeyuv
			case $anyKeyuv in
				*)
					checkCpu
				;;
			esac
		;;
		n|N)
			echo
			echo
			echo -n "The ${freq} overclock/undervolt mods were NOT installed. Press enter to continue: "
			read anyKeynotuv
			case $anyKeynotuv in
				*)
					undervoltMenu
				;;
			esac
		;;
	esac
}

disableOc()
{
	echo
	echo -n "This will disable all Overclocking/Undervolting, continue? (y/n) : "
	read disableOc
	case $disableOc in
		y|Y)
			busybox mount -o remount,rw /system
			busybox sed -i 's|doOverclock=.*|doOverclock=0|' /system/etc/init.d/99oc
			echo
			echo -n "You must reboot for the changes to take effect, reboot now? (y/n) : "
			read rebootNow
			case $rebootNow in
				y|Y)
					reboot
				;;
			esac
		;;
		n|N)
			echo
			echo -n "Overclocking/Undervolting was not disbaled. Press enter to continue: "
			read anyKeymenu
			case $anyKeymenu in
				*)
				;;
			esac
		;;
	esac
}

disableMods()
{
	
	if busybox [ -n "$( busybox grep doMods=1 /system/xbin/modcentral )" ]; then
	echo -n "JakebitesMods are currently running, would you like to disable them? (y/n) : "
		read offMods
		case $offMods in
			y|Y)
				busybox mount -o remount,rw /system
				busybox sed -i 's|doMods=.*|doMods=0|' /system/xbin/modcentral
				busybox rm /system/etc/init.d/99mods
				busybox rm /system/etc/init.d/99oc
				busybox rm /system/etc/init.d/99gov
				busybox rm /system/etc/init.d/99zip
				busybox rm /system/etc/init.d/99logger
				busybox rm /system/etc/init.d/99sysctl
				busybox rm /system/etc/init.d/99cron
				busybox rm /system/etc/init.d/99oc
				busybox rm /system/etc/init.d/99oc
				busybox cp -f /data/mods/build.prop
				echo -n "You must reboot for the changes to take effect, reboot now? (y/n) : "
				read rebootNow
				case $rebootNow in
					y|Y)
						reboot
					;;
				esac
			;;
			n|N)
				echo
				echo
				echo -n "JakebitesMods remain enabled, press enter to continue: "
				read anyKeymenu
				case $anyKeymenu in
					*)
					;;
				esac
				echo
				echo
			;;			
		esac
	else
	echo -n "JakebitesMods are currently not running. enable them now? (y/n) : "
		read onMods
		case $onMods in
			y|Y)
				busybox mount -o remount,rw /system
				busybox sed -i 's|doMods=.*|doMods=1|' /system/xbin/modcentral
				busybox cp /data/mods/* /system/etc/init.d/
				busybox chmod -R 755 /system/etc/init.d/
				echo
				echo
				echo "JakebitesMods enabled."
				echo -n "You must reboot for the changes to take effect, reboot now? (y/n) : "
				read rebootNow
				case $rebootNow in
					y|Y)
						reboot
					;;
				esac
			;;
			n|N)
				echo
				echo
				echo -n "JakebitesMods remains disabled, press enter to continue: "
				read anyKeymenu
				case $anyKeymenu in
					*)
					;;
				esac
				echo
				echo
			;;			
		esac
	fi
}

navigateMenu()
{
	 	echo "============================================="
		echo "|                                           |"
		echo "| 1) Navigate to the main menu              |"
		echo "| 2) Navigate to the Overclock menu         |"
		echo "|                                           |"
		echo "============================================="
		echo -n "Choose where you would like to go: "
		read chooseMenu
		case $chooseMenu in
			2) undervoltMenu
			;;
		esac 		
}
checkCpu()
{
	if busybox [ -n "$( busybox grep doOverclock=1 /system/etc/init.d/99oc )" ]; then
		if busybox [ -n "$( busybox grep doFreq=1 /system/etc/init.d/99oc )" ]; then
		echo
		echo "     Undervolted at 1Ghz         "
		echo "================================"
		echo "|                              |"
		echo "| Mhz | 300 | 600 | 800 | 1000 |"
		echo "|------------------------------|"
		echo "|Volts| 20  | 30  | 40  |  50  |"
		echo "|                              |"
		echo "================================"
		echo
			echo "Currently your governor is:"
			cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
			echo -n "Press enter to continue: "
			read anyKeymenu
			case $anyKeymenu in
				*) navigateMenu
				;;
			esac
		elif busybox [ -n "$( busybox grep doFreq=2 /system/etc/init.d/99oc )" ]; then
		echo
		echo "Overclocked/Undervolted at 1.1Ghz"
		echo "================================"
		echo "|                              |"
		echo "| Mhz | 300 | 600 | 800 | 1100 |"
		echo "|------------------------------|"
		echo "|Volts| 20  | 30  | 40  |  55  |"
		echo "|                              |"
		echo "================================"
		echo
			echo "Currently your governor is:"
			cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
 			echo -n "Press enter to continue: "
			read anyKeymenu
			case $anyKeymenu in
				*) navigateMenu
				;;
			esac
		elif busybox [ -n "$( busybox grep doFreq=3 /system/etc/init.d/99oc )" ]; then
		echo
		echo "Overclocked/Undervolted at 1.2Ghz"
		echo "================================"
		echo "|                              |"
		echo "| Mhz | 300 | 600 | 800 | 1200 |"
		echo "|------------------------------|"
		echo "|Volts| 20  | 30  | 40  |  60  |"
		echo "|                              |"
		echo "================================"
		echo
			echo "Currently your governor is:"
			cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
			echo -n "Press enter to continue: "
			read anyKeymenu
			case $anyKeymenu in
				*) navigateMenu
				;;
			esac 
		elif busybox [ -n "$( busybox grep doFreq=4 /system/etc/init.d/99oc )" ]; then
		echo
		echo "Overclocked/Undervolted at 1.25Ghz"
		echo "================================"
		echo "|                              |"
		echo "| Mhz | 300 | 600 | 800 | 1250 |"
		echo "|------------------------------|"
		echo "|Volts| 20  | 30  | 40  |  65  |"
		echo "|                              |"
		echo "================================"
		echo
			echo "Currently your governor is:"
			cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	 		echo -n "Press enter to continue: "
			read anyKeymenu
			case $anyKeymenu in
				*) navigateMenu
				;;
			esac 
		elif busybox [ -n "$( busybox grep doFreq=5 /system/etc/init.d/99oc )" ]; then
		echo
		echo "Overclocked/Undervolted at 1.3Ghz"
		echo "================================"
		echo "|                              |"
		echo "| Mhz | 300 | 600 | 800 | 1300 |"
		echo "|------------------------------|"
		echo "|Volts| 20  | 30  | 40  |  70  |"
		echo "|                              |"
		echo "================================"
		echo
			echo "Currently your governor is:"
			cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	 		echo -n "Press enter to continue: "
			read anyKeymenu
			case $anyKeymenu in
				*) navigateMenu
				;;
			esac 
		fi
	else
		echo
		echo "You're running stock voltages at 1Ghz."
			echo "Currently your governor is:"
			cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	 		echo -n "Press enter to continue: "
			read anyKeymenu
			case $anyKeymenu in
				*) navigateMenu
				;;
			esac 
		
	fi
	
}


checkMods()
{
	busybox mount -o remount,rw /system
	if busybox [ ! -f /system/etc/init.d/99mods ]; then
	echo -n "Jakebites mods have been disabled by the user, please re-enable them before checking that the mods are working, press enter to continue: "
		read anyKeymenu
		case $anyKeymenu in
			*)
			;;
		esac
	else
		if busybox [ -n "$( busybox grep doOnboot=0 /system/etc/init.d/99mods )" ]; then
		echo -n "No mods are currently enabled, please enable init support for them to work, press enter to continue: "
			read anyKeymenu
			case $anyKeymenu in
				*)
				;;
			esac
		else
			if busybox [ -n "$( busybox grep doSysctl=0 /system/etc/init.d/99sysctl )" ]; then
			echo
			echo " "
			echo "No good, something went wrong with sysctl or it is disbaled."
			echo " "
			else
			echo
			echo " "
			echo "Sysctl's good."
			echo " "
			echo "Checking for cron's session ID: "
			pgrep -f crond
				if [ -z "$?" ]; then
				echo " "
				echo "No good, something went wrong with cron or it is disbaled.";
				echo " "
				else
				echo "Cron's running."
				echo
					if busybox [ -n "$( busybox grep doZip=0 /system/etc/init.d/99zip )" ]; then
					echo "No good, something went wrong with the zipalign mod or it is disabled."
					echo
					else
					echo "Zipalign at boot is working."
					echo
						if busybox [ -n "$( busybox grep doLogger=0 /system/etc/init.d/99logger )" ]; then
						echo "Logger is enabled, disable to save battery."
						else
						echo "Logger is disabled, which saves battery."
							if busybox [ -n "$( busybox grep doRecovery=0 /system/etc/init.d/99recovery )" ]; then
							echo
							echo "Recovery at boot currently disabled."
							echo
								if busybox [ -n "$( busybox grep doOverclock=0 /system/etc/init.d/99oc )" ]; then
								echo " "
								echo -n "No overclock/undervolt running, everything else checks out, your mods are all running fine. Press enter to see CPU info: "
									read checkCpu
									case $checkCpu in
										*) checkCpu
										;;
									esac				
								else	
								echo
								echo -n "Overclock/undervolt running fine, everything checks out, your mods are all running fine. Press enter to see CPU info: "
								read checkCpu
								case $checkCpu in
									*) checkCpu
									;;
								esac
								fi
							else
							echo
							echo "Recovery at boot currently enabled."
							echo
								if busybox [ -n "$( busybox grep doOverclock=0 /system/etc/init.d/99oc )" ]; then
								echo " "
								echo -n "No overclock/undervolt running, everything else checks out, your mods are all running fine. Press enter to see CPU info: "
								read checkCpu
								case $checkCpu in
									*) checkCpu
									;;
								esac			
								else
								echo
								echo -n "Overclock/undervolt running fine, everything checks out, your mods are all running fine. Press enter to see CPU info: "
								read checkCpu
								case $checkCpu in
									*) checkCpu
									;;
								esac
								fi
							fi					
						fi
					fi
				fi
			fi	
		fi
	fi
}

doInit()
{
	if busybox [ -n "$( busybox grep doOnboot=1 /system/etc/init.d/99mods )" ]; then
	echo -n "Your init is already running fine, press enter to continue: "
		read anyKeymenu
		case $anyKeymenu in
			*)
			;;
		esac
	else
	echo -n "Your ROM currently doesn't support init, turn init on now? (y/n) : "
		read initonMod
		case $initonMod in
			y|Y)
				busybox mount -o remount,rw /system
				busybox mkdir /system/usr/bin/
				busybox cp /data/init/pm_init.sh /system/usr/bin/
				chmod 755 /system/usr/bin/pm_init.sh
				echo
				echo
				echo -n "You must reboot for the changes/mods to take effect, reboot now? (y/n) : "
				read rebootNow
				case $rebootNow in
					y|Y)
						reboot
					;;
				esac
			;;
			n|N)
				echo
				echo
				echo -n "Init not enabled, press enter to continue: "
				read anyKeymenu
				case $anyKeymenu in
					*)
					;;
				esac
				echo
				echo
			;;			
		esac
	fi
}


# Main menu

# Overclock/Undervolt menu

	undervoltMenu()
	{
		echo "============================================="
		echo "|                                           |"
		echo "| This will enable overclocking and/or      |"
		echo "| undervolting on your device. Not all      |"
		echo "| devices can handle these frequencies      |"
		echo "| or voltages. For that reason a script     |"
		echo "| will be run that will boot you into       |"
		echo "| clockworkmod recovery the next time you   |"
		echo "| reboot. Weather it be from the phone      |"
		echo "| crashing from the overclocking and/or     |"
		echo "| the undervolting, or if you just reboot   |"
		echo "| it yourself, you will be brought to       |"
		echo "| clockworkmod recovery. At which point you |"
		echo "| you can just reflash my mods .zip and the |"
		echo "| overclock/undervolt will be reset.        |"
		echo "|                                           |"
		echo "| This is a safety measure taken to prevent |"
		echo "| bricking any phones.                      |"
		echo "|                                           |"
		echo "============================================="
		echo
		echo -n "Please confirm you have read and understand this safety precaution. (y/n) : "
		read confirmSafe
		case $confirmSafe in
			y|Y)
			;;
			n|Y)
				exit
			;;
		esac

		
		echo "============================================="
		echo "| This is the new overclock/unvervolt menu. |"
		echo "| As you can see I've added a few things!   |"
		echo "| Set your CPU however you'd like. :)       |"
		echo "|                                           |"
		echo "| 1) Undervolt 1.0 GHZ                      |"
		echo "| 2) Overclock/Undervolt 1.1 GHZ            |"
		echo "| 3) Overclock/Undervolt 1.2 GHZ            |"
		echo "| 4) Overclock/Undervolt 1.25 GHZ           |"
		echo "| 5) Overclock/Undervolt 1.3 GHZ            |"
		echo "| 6) Disable all Overlcock/Undervolt        |"
		echo "| 7) Check current CPU settings             |"
		echo "| 8) Go back to the main menu               |"
		echo "| 9) Exit ModCentral                        |"
		echo "|                                           |"
		echo "============================================="
		echo
		echo -n "Please choose which setting you would like."
		read ocuvChoice
		case $ocuvChoice in
			1) undervoltMods 1000mhz					;;
			2) undervoltMods 1100mhz					;;
			3) undervoltMods 1200mhz					;;
			4) undervoltMods 1250mhz					;;
			5) undervoltMods 1300mhz					;;
			6) disableOc								;;
			7) checkCpu									;;
			9) exit										;;
	
		esac
	}

echo "============================================="
echo "|                                           |"
echo "| Welcome to the Mod Central, this is a new |"
echo "| project that I will be updating as I go.  |"
echo "| Here you can customize most of my mods    |"
echo "| to an extent. Hope you like it!           |"
echo "|                                           |"
echo "============================================="
echo
echo

# Mod Central main menu

exitLoop=0
while busybox [ $exitLoop -eq 0 ]; do
echo "============================================="
echo "|                                           |"
echo "| 1) Sysctl Mod                             |"
echo "| 2) Cron Mod                               |"
echo "| 3) Zipalign Mod                           |"
echo "| 4) InteractiveX Governor Mod              |"
echo "| 5) Logger Mod                             |"
echo "| 6) Overclock/Undervolt Mods               |"
echo "| 7) V6 Supercharger Mods by zeppelinrox    |"
echo "| 8) Check Mods                             |"
echo "| 9) Enable recovery on each reboot         |"
echo "| 10) Enable init for ROMS without          |"
echo "| 11) Disable/re-enable all mods            |"
echo "| 12) Reboot                                |"
echo "| 13) Exit ModCentral                       |"
echo "|                                           |"
echo "============================================="
echo -n "Please choose what you would like to do."
read mainChoice
case $mainChoice in
	1) sysctlMods 					;;
	2) cronMods						;;
	3) zipMods	 					;;
	4) govMods						;;
	5) loggerMods 					;;
	6) undervoltMenu				;;
	7) doSupercharge 				;;
	8) checkMods					;;
	9) bootRecovery					;;
	10) doInit						;;
	11) disableMods					;;
	12) reboot						;;
	13) exit						;;
esac
done
