#!/system/bin/sh

# Variable
doGov=1

# enable the conservative governor by default
busybox mount -o remount,rw /system
if busybox [ $doGov -eq 1 ]; then
insmod /system/lib/modules/cpufreq_conservative.ko
echo conservative > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
fi